### Get all available meals
GET https://{{hostname}}/meals

### Login picnic
POST https://{{hostname}}/picnic/15/user/login
Content-Type: application/json

{
  "key": "manon_besemer@hotmail.com",
  "secret": "{{password}}",
  "client_id": 30100
}