### Get all available meals
GET https://{{hostname}}/meals

### Login picnic
POST https://{{hostname}}/picnic/15/user/login
Content-Type: application/json

{
  "key": "manon_besemer@hotmail.com",
  "secret": "{{password}}",
  "client_id": 30100
}

> {%
    client.global.set("x-picnic-auth", response.headers.valueOf('x-picnic-auth'));
%}

### Search
GET https://{{hostname}}/picnic/15/search?search_term=kipfilet
Content-Type: application/json
User-Agent: okhttp/3.12.2
x-picnic-auth: {{x-picnic-auth}}

{
  "key": "manon_besemer@hotmail.com",
  "secret": "{{password}}",
  "client_id": 30100
}