# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.2

commands:
  build:
    steps:
      - checkout
      - run: npm install
  test:
    steps:
      - run: npm run test
  deploy:
    steps:
      - run: cdk deploy --require-approval never

jobs:
  build:
    executor: aws-cli/default
    steps:
      - build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    machine:
      image: cimg/node:21.6.1
    steps:
      - attach_workspace:
          at: .
      - test

  deploy:
    machine:
      image: cimg/node:21.6.1
    steps:
      - attach_workspace:
          at: .
      - deploy

workflows:
  build:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test